### PR TITLE
Fix create

### LINKED ISSUE #29: "Create" (and similar words) give too few
Create -> 1, Creative -> 2, Creativity -> 4

### PR DESCRIPTION
**Pull request by skeate**
fixes #29

### CODE REVIEW

**Comment by wooorm** [comment]
Nice! If I run `sed -n '/^creat/p' < /usr/share/dict/words` (find words starting with `creat`), I get the following matches:

```
creat
creatable
create
createdness
creatic
creatine
creatinephosphoric
creatinine
creatininemia
creatinuria
creation
creational
creationary
creationism
creationist
creationistic
creative
creatively
creativeness
creativity
creatophagous
creator
creatorhood
creatorrhea
creatorship
creatotoxism
creatress
creatrix
creatural
creature
creaturehood
creatureless
creatureliness
creatureling
creaturely
creatureship
creaturize
```

I think most cases of `creat*` are syllables `cre-at`, but for `creatu*` I think that’s not the case: [`creature` is `crea-ture`](https://www.howmanysyllables.com/words/creature)

**Comment by skeate** [comment]
Dang, I checked a [regex dictionary](https://www.visca.com/regexdict/) and I guess I just overlooked "creature". Added a `[^u]` to fix that.

**Comment by skeate** [comment]
Better, added `"creat": 2` test case and used a negative lookahead.

**Comment by skeate** [comment]
Would like some advice here. I also realized this doesn't cover prefixed versions, like "recreate", which is easy to fix by removing the `^`.  However, things like "procreation" and "recreation" still fail because (I think) it extracts the "-tion" suffix first, and then "creat" can't match because it's lacking the t.

I can fix this by adding "creation" completely as a triple-syllable "suffix", but that seems wrong. Alternatively, add them as problematic words (which I already did with "creation"). Maybe the best would to modify the code to check for pre-/suffixes on known problematic words, but that's definitely a more extensive change. It would be much more general-purpose, though, catching things like "pulseless"

**Comment by wooorm** [comment]
Ah thanks for the start, I figured it out (see the commit referenced above)!

**Pull request closed without merging**
